export enum OmegaPayTransactionStatusEnum {
  OK = "OK",
  FAILED = "FAILED",
  PENDING = "PENDING",
  REJECTED = "REJECTED",
  CANCELED = "CANCELED",
}

export enum OmegaPayWebhookEventEnum {
  TRANSACTION_CREATED = "TRANSACTION_CREATED",
  TRANSACTION_PAID = "TRANSACTION_PAID",
  TRANSACTION_CANCELED = "TRANSACTION_CANCELED",
  TRANSACTION_REFUNDED = "TRANSACTION_REFUNDED",
  TRANSACTION_CHARGED_BACK = "TRANSACTION_CHARGED_BACK",
}
